# Generated by Django 5.1.3 on 2025-01-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_post_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.CharField(max_length=300),
        ),
    ]
