# Generated by Django 5.1.3 on 2025-01-22 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_liked',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
