# Generated by Django 5.1.3 on 2025-01-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_users_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
