# Generated by Django 5.1.3 on 2025-01-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_remove_post_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["time"]},
        ),
    ]
